[package]
name = "vulkan-reference"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
raw-window-handle = "0.6.2"
winit = { version = "0.30.12", features = ["rwh_06"] }
